version: "3.8"

services:
  nginx:
    image: aungkhantsoe/custom-nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    depends_on:
      - users_services
      - contracts_services

  users_services:
    image: aungkhantsoe/users_services:latest
    container_name: users_services
    restart: always
    expose:
      - "8000"
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: laravel_crud_api
      DB_USERNAME: laravel
      DB_PASSWORD: secret
    depends_on:
      - db

  contracts_services:
    image: aungkhantsoe/contracts_services:latest
    container_name: contracts_services
    restart: always
    expose:
      - "8000"
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: laravel_crud_api
      DB_USERNAME: laravel
      DB_PASSWORD: secret
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel_crud_api
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
