AWSTemplateFormatVersion: '2010-09-09'
Description: ECS Fargate service with ALB for Laravel users_services microservice

Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: VPC ID where ECS and ALB will be deployed
  SubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
    Description: Two public subnet IDs for ALB and ECS tasks
  EcrImageUri:
    Type: String
    Description: Full ECR image URI, e.g. 123456789012.dkr.ecr.region.amazonaws.com/user-service:latest

Resources:
  # ALB Security Group
  ALBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security Group for Application Load Balancer
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: -1
          FromPort: 0
          ToPort: 65535
          CidrIp: 0.0.0.0/0

  # ECS Tasks Security Group - allow only ALB SG inbound
  ECSSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security Group for ECS tasks
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          SourceSecurityGroupId: !Ref ALBSecurityGroup
      SecurityGroupEgress:
        - IpProtocol: -1
          FromPort: 0
          ToPort: 65535
          CidrIp: 0.0.0.0/0

  # ECS Cluster
  UserCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: user-service-cluster

  # IAM Role for ECS Task execution
  UserTaskExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: user-task-execution-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy

  # ECS Task Definition
  UserTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: user-service-task
      Cpu: '512'
      Memory: '1024'
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      ExecutionRoleArn: !GetAtt UserTaskExecutionRole.Arn
      RuntimePlatform:
        CpuArchitecture: X86_64
        OperatingSystemFamily: LINUX
      ContainerDefinitions:
        - Name: user-container
          Image: !Ref EcrImageUri
          PortMappings:
            - ContainerPort: 80
          Essential: true

  # ALB
  AppLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: user-service-alb
      Subnets: !Ref SubnetIds
      SecurityGroups:
        - !Ref ALBSecurityGroup
      Scheme: internet-facing
      Type: application

  # Target Group
  AppTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: user-service-target-group
      Port: 80
      Protocol: HTTP
      VpcId: !Ref VpcId
      TargetType: ip
      HealthCheckPath: /api/users/

  # ALB Listener
  AppListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref AppLoadBalancer
      Port: 80
      Protocol: HTTP
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref AppTargetGroup

  # ECS Service
  UserService:
    Type: AWS::ECS::Service
    DependsOn: AppListener
    Properties:
      Cluster: !Ref UserCluster
      ServiceName: user-service
      LaunchType: FARGATE
      DesiredCount: 1
      TaskDefinition: !Ref UserTaskDefinition
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          Subnets: !Ref SubnetIds
          SecurityGroups:
            - !Ref ECSSecurityGroup
      LoadBalancers:
        - ContainerName: user-container
          ContainerPort: 80
          TargetGroupArn: !Ref AppTargetGroup
      DeploymentConfiguration:
        MaximumPercent: 200
        MinimumHealthyPercent: 50

Outputs:
  LoadBalancerDNSName:
    Description: DNS name of the load balancer
    Value: !GetAtt AppLoadBalancer.DNSName
