name: Laravel Microservices CI/CD

on:
  push:
    branches:
      - main

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      run: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

    - name: Build & Push users_services
      run: |
        docker build -t $DOCKER_USERNAME/users_services:latest ./users_services
        docker push $DOCKER_USERNAME/users_services:latest

    - name: Build & Push contracts_services
      run: |
        docker build -t $DOCKER_USERNAME/contracts_services:latest ./contracts_services
        docker push $DOCKER_USERNAME/contracts_services:latest

    - name: Build & Push custom-nginx
      run: |
        docker build -t $DOCKER_USERNAME/custom-nginx:latest ./nginx
        docker push $DOCKER_USERNAME/custom-nginx:latest

    - name: Deploy on EC2
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd ~/laravel-microservices
          docker compose -f docker-compose.prod.yml pull
          docker compose -f docker-compose.prod.yml up -d

          echo "Running Laravel setup"
          docker exec $DOCKER_USERNAME/users_services composer install --no-interaction --prefer-dist
          docker exec $DOCKER_USERNAME/users_services php artisan migrate:fresh --seed --force
          docker exec $DOCKER_USERNAME/users_services php artisan config:cache

          docker exec $DOCKER_USERNAME/contracts_services composer install --no-interaction --prefer-dist
          docker exec $DOCKER_USERNAME/contracts_services php artisan migrate:fresh --seed --force
          docker exec $DOCKER_USERNAME/contracts_services php artisan config:cache
