name: Deploy to EC2

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up SSH key
      run: |
        echo "${{ secrets.EC2_SSH_KEY }}" > ec2_key.pem
        chmod 600 ec2_key.pem

    - name: SSH to EC2 and deploy with Docker Compose
      run: |
        ssh -o StrictHostKeyChecking=no -i ec2_key.pem ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} "
          set -e

          echo 'Cloning or pulling latest code...'
          if [ ! -d laravel-microservices ]; then
            git clone https://github.com/Aung-KhantSoe/laravel-microservices.git laravel-microservices
          fi
          cd laravel-microservices
          git pull origin main

          echo 'Rebuilding containers...'
          docker compose down
          docker compose build
          docker compose up -d

          echo 'Running Laravel setup in users_services...'
          docker exec users_services php artisan migrate --force || true
          docker exec users_services php artisan config:cache || true

          echo 'Running Laravel setup in contracts_services...'
          docker exec contracts_services php artisan migrate --force || true
          docker exec contracts_services php artisan config:cache || true
        "
